apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-np
spec:
  type: Nodeport
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080
  selector:
    app: guestbook-ui
